[[test_cases]]
part = 1
expected = "357"
input = """
987654321111111
811111111111119
234234234234278
818181911112111
"""

[[test_cases]]
part = 2
expected = "3121910778619"
input = """
987654321111111
811111111111119
234234234234278
818181911112111
"""
