[[test_cases]]
part = 1
expected = "4277556"
input = """
123 328  51 64 
 45 64  387 23 
  6 98  215 314
*   +   *   +  
"""

[[test_cases]]
part = 2
expected = "3263827"
input = """
123 328  51 64 
 45 64  387 23 
  6 98  215 314
*   +   *   +  
"""
